# Generated by Django 5.1.1 on 2024-11-30 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default='https://images.tfbfoundation.org/default_profile.png/', max_length=300)),
                ('profession', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('current_address', models.TextField()),
                ('phone_no', models.CharField(max_length=12)),
                ('district', models.CharField(max_length=200)),
                ('sub_district', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=200)),
                ('verification_code', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favourites', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
