# Generated by Django 5.1.1 on 2024-10-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfbAccountAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.CharField(default='https://images.tfbfoundation.org/default_profile.png/', max_length=300),
        ),
    ]
