# Generated by Django 5.0.6 on 2024-10-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodhidharaNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('fb_post_id', models.TextField(blank=True, null=True)),
                ('fb_video_ids', models.JSONField(blank=True, null=True)),
                ('fb_photo_ids', models.JSONField(blank=True, null=True)),
                ('fb_post_react', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
