# Generated by Django 5.1.1 on 2024-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhidharaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodhidharanews',
            name='views',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
