# Generated by Django 5.1.1 on 2024-11-20 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhidharaAPI', '0003_alter_bodhidharanews_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodhidharaNewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bodhidharaAPI.bodhidharanews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodhidharaNewsCommentReply1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply1', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies1', to='bodhidharaAPI.bodhidharanewscomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodhidharaNewsCommentReply2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply2', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies2', to='bodhidharaAPI.bodhidharanewscommentreply1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
